workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
    - if: $CI_COMMIT_TAG

#############################################
# Global variables for all CI jobs
#############################################
variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: "0"

  GCC_VERSION: "ml gcc/10.3.1"
  CLANG_VERSION: "ml clang/14.0.6"
  GCC_MATRIX_VERSION: "ml gcc/13.3.1"
  MATRIX_CUDA_VERSION: "ml cuda/12.6"
  ROCM_VERSION: "ml rocm/7.0.0"
  ROCMCC_VERSION: "ml rocmcc/7.0.0-magic"
  CMAKE_VERSION: "ml cmake/3.23.1"

  TENSORFEM_CI: "1"
  CPU_MACHINE: "dane"
  H100_MACHINE: "matrix"
  HIP_MACHINE: "tuolumne"

  TENSORFEM_TPLS_FARM: "/usr/workspace/boba_dev/tensorfem_build_farms/2026_08_11"

include:
  - project: 'lc-templates/id_tokens'
    file: 'id_tokens.yml'

stages:
  - prep
  - build_and_test

#############################
#   Set defaults
#############################

default:
  timeout: 1 hour
  artifacts:
    expire_in: 2 weeks

.shell_cpu:
  tags:
    - dane
    - batch
  variables:
    LLNL_SLURM_SCHEDULER_PARAMETERS: "--nodes=1 --ntasks=90 --time=00:20:00 --partition=pci --reservation=ci"

.shell_h100:
  tags:
    - matrix
    - batch
  variables:
    LLNL_SLURM_SCHEDULER_PARAMETERS: "--nodes=1 --ntasks=1 --gres=gpu:4 --time=00:20:00 --cpus-per-task=112 --partition=pdebug --exclusive"

.shell_hip:
  tags:
    - tuolumne
    - batch
  variables:
    LLNL_FLUX_SCHEDULER_PARAMETERS: "--queue pci -N 1 -n 1"
    JACAMAR_SCHEDULER_DEBUG: "1"

.tensorfem_base:
  before_script:
    - git rev-parse HEAD
    - pwd
    - export TENSORFEM_TPLS_FARM="${TENSORFEM_TPLS_FARM}"

#############################
#   Prep
#############################
ci_sanity_checks:
  extends:
    - .shell_cpu
    - .tensorfem_base
  stage: prep
  script:
    - echo Ensuring build farm permissions are correct
    - chgrp boba_dev "${TENSORFEM_TPLS_FARM}" || echo "You are not the owner of this TPL build farm"
    - chgrp boba_dev "${TENSORFEM_TPLS_FARM}/tpl" || echo "You are not the owner of this TPL build farm"
    - chgrp -R boba_dev "${TENSORFEM_TPLS_FARM}/tpl" || echo "You are not the owner of this TPL build farm"
    - chmod g+rwxs "${TENSORFEM_TPLS_FARM}" || echo "You are not the owner of this TPL build farm"
    - chmod g+rwxs "${TENSORFEM_TPLS_FARM}/tpl" || echo "You are not the owner of this TPL build farm"
    - chmod -R g+rwxs "${TENSORFEM_TPLS_FARM}/tpl" || echo "You are not the owner of this TPL build farm"

#############################
#   Build and test
#############################
cpu_build_and_test:
  extends:
    - .shell_cpu
    - .tensorfem_base
  stage: build_and_test
  needs: ["ci_sanity_checks"]
  script:
    - ${GCC_VERSION}
    - squeue -p pci
    - time srun -n 1 make all TENSORFEM_CI=1 BOBA_DEBUG=1 BOBA_HDF5=1 -j 36 --output-sync
    - time srun -n 1 python3 "${TENSORFEM_TPLS_FARM}/tpl/BoBa/ci.py" --debug
    - make clean
    - squeue -p pci
    - time srun -n 1 make all TENSORFEM_CI=1 BOBA_HDF5=1 -j 36 --output-sync
    - time srun -n 1 python3 "${TENSORFEM_TPLS_FARM}/tpl/BoBa/ci.py"

.h100_build_and_test:
  extends:
    - .shell_h100
    - .tensorfem_base
  stage: build_and_test
  needs: ["ci_sanity_checks"]
  script:
    - ${GCC_MATRIX_VERSION}
    - ${MATRIX_CUDA_VERSION}
    - squeue -p pdebug
    - time srun -n 1 make all TENSORFEM_CI=1 BOBA_CUDA=1 BOBA_CUTENSOR=1 BOBA_UMPIRE=1 BOBA_ADIAK=1 -j 24 --output-sync
    - time srun -n 1 python3 "${TENSORFEM_TPLS_FARM}/tpl/BoBa/ci.py" --umpire

.hip_build_and_test:
  extends:
    - .shell_hip
    - .tensorfem_base
  stage: build_and_test
  needs: ["ci_sanity_checks"]
  script:
    - ${ROCM_VERSION}
    - ${ROCMCC_VERSION}
    - module list
    - flux queue list || true
    - flux resource list || true
    - time flux run -N 1 -n 1 --exclusive make all TENSORFEM_CI=1 BOBA_HIP=1 BOBA_HIPTENSOR=1 BOBA_UMPIRE=1 BOBA_ADIAK=1 -j 32 --output-sync
    - time flux run -N 1 -n 1 --exclusive python3 "${TENSORFEM_TPLS_FARM}/tpl/BoBa/ci.py" --umpire
